#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp -r 0.org 0
runApplication blockMesh
runApplication setFields
runApplication decomposePar
runParallel `getApplication` 2

# ----------------------------------------------------------------- end-of-file
