#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp -r 0.org 0
runApplication blockMesh
runApplication setFields
runApplication decomposePar
touch test.foam
touch processor0/test.foam
touch processor1/test.foam
touch processor2/test.foam
touch processor3/test.foam
#runParallel `getApplication` 4
foamJob -parallel -screen interDyMFoam


# ----------------------------------------------------------------- end-of-file
