#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp -r 0.org 0
runApplication blockMesh
runApplication topoSet
runApplication subsetMesh -overwrite c0 -patch walls
runApplication setFields
touch jet.foam

#reactingFoam

runApplication decomposePar
foamJob -parallel -screen reactingFoam


# ----------------------------------------------------------------- end-of-file
